### ISSUE TITLE
port to python

### ISSUE THREAD

**Issue by andro-galexy** [MinhasKamal/GenderRecognizer#3]
Hi, would you mind porting this project to python?

**Comment by MinhasKamal** [comment]
Sorry, could not understand. Can you please clarify?

**Comment by andro-galexy** [comment]
I mean is it feasible to write same code in python.

**Comment by MinhasKamal** [comment]
OpenCV has python API too, so of course you can do the same thing with python. Feel free if you have any other query.

Sorry for the late reply :)
